default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_development
  username: postgres
  password: admin
  host: localhost
  port: 5432

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
  username: postgres
  password: admin
